### ISSUE TITLE
Imported logins don’t sync

### ISSUE THREAD

**Issue by danielearwicker** [louisabraham/ffpass#11]
I have three Firefox devices: a Mac laptop, a Windows laptop and an iPhone.

I have syncing of logins working between l them: I’ve tested saving a login on the Mac and seen it appear in the list of logins on the iPhone after syncing. (I’ve also seen that deletion of logins is synced).

I used `ffpass` to import a csv into Firefox on the Mac, and it appeared to work: the hundreds of imported logins now appear in the Saved Logins list, and they are autosuggested when I visit the sites.

But those imported logins are not synced to the other devices. New ones added interactively are synced, but the sync operation seems to totally ignore the logins that I imported with `ffpass`.

I noticed that all the entries for the imported logins in `logins.json` had the same time stamp, so I tried changing it to the value for current epoch time, restarted Firefox and requested resync on all devices, but that didn’t work.

**Comment by louisabraham** [comment]
Hi,
When I wrote this script, I was able to import all my passwords and have them synced.
I have no idea about the mechanism of synchronization of Firefox so I really cannot help, that's why I'm closing this issue. 
I can remember that I thought that it didn't work at first, but after a few hours the passwords worked on my mobile device.

If you see a pattern for the attributes in `logins.json` that makes the sync work for you, I'll be glad to improve my code with it.

**Comment by ezequielv** [comment]
[...]
> I used `ffpass` to import a csv into Firefox on the Mac, and it appeared to work: the hundreds of imported logins now appear in the Saved Logins list, and they are autosuggested when I visit the sites.
> 
> But those imported logins are not synced to the other devices. New ones added interactively are synced, but the sync operation seems to totally ignore the logins that I imported with `ffpass`.
[...]

:+1: I've just experienced the same issue with `ffpass` on Linux Mint (based on Ubuntu-18.04). I'd love to see this working, and I guess I'll just wait (triggering the "synching" process by hand on the browser instance that has the imported logins, *and* on every other _connected_ browser has not solved the issue, either).

**Comment by xliiv** [comment]
I'm experiencing the same.

**Comment by leetking** [comment]
I'm meeting same problems, It's sad. :sob:
