### ISSUE TITLE
SubstrateUnderrunError: 94-octet short

### ISSUE THREAD

**Issue by netllama** [louisabraham/ffpass#16]
I'm trying to use this tool to export my Firefox-65.0 passwords on a Linux (Fedora) system, and it is crashing:
```
$ ffpass export > passwords.csv
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ffpass/__init__.py", line 337, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/ffpass/__init__.py", line 260, in main_export
    logins = exportLogins(key, jsonLogins)
  File "/usr/local/lib/python3.6/site-packages/ffpass/__init__.py", line 169, in exportLogins
    decodeLoginData(key, encUsername),
  File "/usr/local/lib/python3.6/site-packages/ffpass/__init__.py", line 125, in decodeLoginData
    asn1data, _ = der_decode(b64decode(data))
  File "/usr/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 1049, in __call__
    raise error.SubstrateUnderrunError('%d-octet short' % (length - len(substrate)))
pyasn1.error.SubstrateUnderrunError: 94-octet short
```

**Comment by louisabraham** [comment]
I'm sorry, I have no idea of what can cause this error.

Can Firefox read correctly your passwords?
Did you leave Firefox open during the process?
Try to add and remove a password manually, and retry.

Can anybody reproduce this error?

**Comment by netllama** [comment]
Firefox has no problems reading my passwords.  Firefox was *not* running when I ran the tool.

Perhaps you should add an exception handler, similar to what was done here?
https://github.com/AlessandroZ/LaZagne/issues/194

**Comment by louisabraham** [comment]
It really seems like your file is corrupted.
I'm not sure I want to add a special case for a malformed file. 

Is there a reason why you don't use LaZagne?
Alternatively, you can easily fork the repo or edit the source directly on your computer to ignore this exception.

**Comment by netllama** [comment]
I'm not sure that I understand how performing exception handling for failures is a special case.  That's a fundamental part of python development.

Firefox certainly doesn't crash when it reads its password database.

If you're not interested in supporting your work, you should probably state that in the README, rather than telling people to make your code tolerant to failures.

**Comment by louisabraham** [comment]
The error basically says that the file doesn't have the right format.
Again, is there a reason why you don't use LaZagne (since they seem to have handled this case)?
