### ISSUE TITLE
(null): can't open file 'ffpass': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by chnbz** [louisabraham/ffpass#2]
Hi,

I using MacOS High Sierra and installed python3 and then via python3 pip ffpass, but whenever I use 

`python3 ffpass import --from passwords.csv` 
 I am getting this error
> (null): can't open file 'ffpass': [Errno 2] No such file or directory

Any ideas how to make it work under MacOS?

**Comment by louisabraham** [comment]
Don't use

    python3 ffpass

Use

    python3 -m ffpass

Normally

    ffpass

should work as well.

**Comment by chnbz** [comment]
Thank you so much for the fast response!

When I use ` python3 -m ffpass` I am getting this error `/usr/local/bin/python3: No module named ffpass.__main__; 'ffpass' is a package and cannot be directly executed`

**Comment by louisabraham** [comment]
Please ensure you have python>=3.5

    python3 --version

Then upgrade the packages

    python3 -m pip install -U pip
    python3 -m pip install -U ffpass

If it still doesn't work, I'll have a look at in in about 3 hours.

**Comment by chnbz** [comment]
`XXX-MacBook:Documents xxx$ python3 -m pip install -U pip
Requirement already up-to-date: pip in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (18.0)
XXX-MacBook:Documents xxx$ python3 -m pip install -U ffpass
Requirement already up-to-date: ffpass in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (0.3.4)
Requirement already satisfied, skipping upgrade: pyasn1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from ffpass) (0.4.4)
Requirement already satisfied, skipping upgrade: pycryptodome in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from ffpass) (3.6.6)
XXX-MacBook:Documents xxx$ python3 --version
Python 3.7.0`

Thank you so much for the help!

**Comment by louisabraham** [comment]
Oh sorry, I'm such an idiot who cannot even launch his how programs.

Just

    ffpass

should work.

**Comment by chnbz** [comment]
Yes, you were right, now it worked! Thank you so much again for your support and this amazing tool!

Do you think it is possible to make and GUI for this script, so it is to more people accessible?

**Comment by louisabraham** [comment]
If you go from chrome to Firefox, be careful, Firefox doesn't import the
mobile bookmarks from Chrome (
https://support.mozilla.org/fr/questions/1230476)

I don't intend to make a GUI, way too hard to maintain for multi platform
and I have a lot of projects already going on.
But anyone is free to do one, that's the principle of open-source :)

**Comment by srulikuk** [comment]
I am having the same issue, cannot run ffpass.
`$ ffpass --help
ffpass: command not found`

`$ python3 -m ffpass --help
/usr/bin/python3: No module named ffpass.__main__; 'ffpass' is a package and cannot be directly executed`

`$ python3 -m pip install -U ffpass
Requirement already up-to-date: ffpass in /home/sruli/.local/lib/python3.6/site-packages (0.3.4)
Requirement already satisfied, skipping upgrade: pycryptodome in /home/sruli/.local/lib/python3.6/site-packages (from ffpass) (3.7.0)
Requirement already satisfied, skipping upgrade: pyasn1 in /home/sruli/.local/lib/python3.6/site-packages (from ffpass) (0.4.4)`

`$ python3 -V
Python 3.6.7`

**Comment by louisabraham** [comment]
It seems that your path doesn't contain the bin folder of your python installation.

Try

    /home/sruli/.local/bin/ffpass

If it works, then you should add /home/sruli/.local/bin to $PATH in your bash profile.

**Comment by srulikuk** [comment]
> Try /home/user/.local/bin/ffpass
Thanks that was it.

**Comment by ymatuhin** [comment]
Same scenario.
```
❯ python3 -m ffpass --help
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: No module named ffpass.__main__; 'ffpass' is a package and cannot be directly executed

❯ python3 -m pip install -U ffpass
Requirement already up-to-date: ffpass in /Users/ym/Library/Python/3.8/lib/python/site-packages (0.4.8)
Requirement already satisfied, skipping upgrade: pyasn1 in /Users/ym/Library/Python/3.8/lib/python/site-packages (from ffpass) (0.4.8)
Requirement already satisfied, skipping upgrade: pycryptodome in /Users/ym/Library/Python/3.8/lib/python/site-packages (from ffpass) (3.9.4)

❯ /Users/ym/Library/Python/3.8/lib/python/site-packages/ffpass --help
zsh: permission denied: /Users/ym/Library/Python/3.8/lib/python/site-packages/ffpass
a```

and 
`chmod +x /Users/ym/Library/Python/3.8/lib/python/site-packages/ffpass` didn't help.
