### ISSUE TITLE
"Firefox password database is empty." but one password already saved in Firefox.

### ISSUE THREAD

**Issue by AshyAspen** [louisabraham/ffpass#20]
Hi, I've ran into an. issue trying to import a csv into Firefox. This is what the terminal gives me...

> Rileys-MacBook-Air:~ rileydumont$ ffpass import -f /Users/rileydumont/Desktop/Passwords.csv -d /Users/rileydumont/Library/Application/Support/Firefox/Profiles/prmmo8pp.default
Firefox password database is empty. Please create it from Firefox.
Rileys-MacBook-Air:~ rileydumont$ 

Which the guide on here says 

> Firefox password database is empty. Please create it from Firefox.

>It means that Firefox currently doens't store any password. ffpass cannot create the password database for security reasons. Just add one password manually to Firefox to create the database.

And doesn't say anything else. However as you can see here...

![Screen Shot 2019-05-30 at 5 06 49 PM](https://user-images.githubusercontent.com/48628344/58665443-e2ce8480-82fe-11e9-92d0-abacebd66eb2.png)

I do have one entry in Firefox. Perhaps there's some incompatibility somewhere I don't know about, or I'm looking at the wrong password keychain? Not really sure what exactly the issue is or where to look anymore. Any guidance?

Running MacOS 10.14.5 and Firefox 67.0

**Comment by louisabraham** [comment]
Hi, thanks for the report.

- did you try without the -d option? ffpass will automatically select the profile if you have only one. If you have multiple profiles, maybe you didn't select the right one?
- can you add and delete one more password and close Firefox?
- can you list all files that are in your profile directory?

**Comment by AshyAspen** [comment]
Like this?

> Rileys-MacBook-Air:~ rileydumont$ ffpass import -f /Users/rileydumont/Desktop/Passwords.csv
usage: ffpass import [-h] [-f FROM_FILE] -d DIRECTORY [-v]
ffpass import: error: the following arguments are required: -d/--directory/--dir
Rileys-MacBook-Air:~ rileydumont$ 

It seems its having trouble finding it perhaps? This is why I directed it here at the profiles folder I found in troubleshooting  information.

![Screen Shot 2019-05-30 at 7 23 58 PM](https://user-images.githubusercontent.com/48628344/58671504-db17db80-8310-11e9-997c-d1fb9d0eec0e.png)
This brings me here...
![Screen Shot 2019-05-30 at 7 27 28 PM](https://user-images.githubusercontent.com/48628344/58671538-ff73b800-8310-11e9-9a93-23f4a2fda530.png)
Which is the only folder in "profiles" and contains all of these...
> signedInUser.json
> addons.json
> addonStartup.json.lz4
> AlternateServices.txt
> bookmarkbackups
> broadcast-listeners.json
> cert9.db
> compatibility.ini
> containers.json
> content-prefs.sqlite
> cookies.sqlite
> crashes
> datareporting
> extension-preferences.json
> extensions
> extensions.json
> favicons.sqlite
> formhistory.sqlite
> gmp
> handlers.json
> key4.db
> logins.json
> minidumps
> permissions.sqlite
> pkcs11.txt
> places.sqlite
> pluginreg.dat
> prefs.js
> saved-telemetry-pings
> search.json.mozlz4
> SecurityPreloadState.txt
> sessionCheckpoints.json
> sessionstore-backups
> sessionstore.jsonlz4
> SiteSecurityServiceState.txt
> storage
> storage-sync.sqlite
> storage.sqlite
> times.json
> TRRBlacklist.txt
> weave
> webappsstore.sqlite
> xulstore.json

Also, I did delete the password in there then tried two other ones to no avail, as well as adding one, immediately removing it, then quiting Firefox.

Perhaps I'm adding the password wrong? The guide does say manually but I'm simply logging in and pressing "save" when it asks me since I didn't see a specifically manual option. (not too familiar with Firefox yet) Im really sorry if this ends up being some stupid simple thing like that that I missed.

See anything wrong?

**Comment by AshyAspen** [comment]
By the way, here's the output without -d using verbose.

>Rileys-MacBook-Air:~ rileydumont$ ffpass import -f /Users/rileydumont/Desktop/Passwords.csv -v
There is more than one profile
usage: ffpass import [-h] [-f FROM_FILE] -d DIRECTORY [-v]
ffpass import: error: the following arguments are required: -d/--directory/--dir
Rileys-MacBook-Air:~ rileydumont$ 

Which is why I looked for the profile through the troubleshooting thing. Though, now that I think about it this doesn't make any sense because that folder only had one folder in it (I assume each account would have its own folder) so something definitely seems wrong.

**Comment by AshyAspen** [comment]
Just realized the issue in my original post.

Instead of /Application\ Support/ to delineate the space in the folder I had replaced it with /Application/Support/ because I thought it was a spelling error and was still receiving an error even with the proper command. 

Which leads me to the error that originally made me think I had a misspelling and caused this whole mess...

> Rileys-MacBook-Air:~ rileydumont$ ffpass import -f /Users/rileydumont/Desktop/Passwords.csv -d /Users/rileydumont/Library/Application\ Support/Firefox/Profiles/prmmo8pp.default
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 339, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 282, in main_import
    logins = readCSV(args.from_file)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 182, in readCSV
    logins.append((rawURL(row["url"]), row["username"], row["password"]))
KeyError: 'url'
Rileys-MacBook-Air:~ rileydumont$ python --version
Python 2.7.10
Rileys-MacBook-Air:~ rileydumont$ python3 --version
Python 3.7.3
Rileys-MacBook-Air:~ rileydumont$ 

I've included the error as well as python version given by two commands which I think may have to do with it.. maybe possibly? I'm a bit of a newb with this stuff but python version seems important and the command I used from the readme installed both, perhaps that's part of it? Anyway, this comes out.

I'm really sorry

**Comment by louisabraham** [comment]
It seems to me that there are 3 different issues:

1. `Firefox password database is empty. Please create it from Firefox.`: This one was due to a wrong path.

2. `There is more than one profile`: I slightly modified this behavior in version 0.4.6, can you update and check again without the `-d` option? Else, please paste the content of `~/Library/Application Support/Firefox/profiles.ini`.

3.  `KeyError: 'url'`: The first line of your CSV should be `url,username,password`. Look at the output of `ffpass export` for an example.

**Comment by AshyAspen** [comment]
- I upgraded ffpass and it works perfect without -d now.

- Regarding issue 3, It seems the issue here was I enabled automatic headers from 1Password. I didn't realize the ones it made were capitalized, so I modified it to "url,username,password" instead of "URL,Username,Password" and the error went away. When I saw "url" I actually thought it had to do with blank urls or ones lacking "https://" at first. Makes more sense now though.

Functioning as intended now that I've "uncapitalized" the headers and upgraded, thank you so much!

**Comment by louisabraham** [comment]
Glad it worked for you :)

Since many users got the same case issue, I just changed the behavior in version 0.4.7. Now it will work even if the header is capitalized. Can you test it with your old CSV file?

Thanks for making ffpass even better :)

**Comment by AshyAspen** [comment]
Just upgraded and tried a csv exported directly from 1password with the "Include Column Names" option selected and it works perfect on the latest version (0.4.7), even with the default capitalization 1Password exports as.

All looks good! Thank you for this wonderful program, its very useful!
