### ISSUE TITLE
I don't know how to use ffpass

### ISSUE THREAD

**Issue by kasperaamodt** [louisabraham/ffpass#21]
Hello! I have tried to figure out how to use this for 5 hours now, and I'm so lost. I have a MacBook Pro, running MacOS Mojave. I have managed to create a .CSV file with all the passwords, exported from chrome with all the passwords. But I don't know how to get them in to Firefox. I don't even know if I should use Terminal or Xcode or whatever. I have installed Python3, and have an app called IDLE and Python Launcher, is that one of the apps I should use?

**Comment by louisabraham** [comment]
Come on, nobody is stupid!

1. Open the terminal (the app with a black icon). In the next steps, whenever you see text `like this`, type it in the terminal window.
2. `python3 -m pip install ffpass` and hit ENTER
3. `ffpass import -f `, then drag and drop the csv file from Finder and hit Enter

It should work, tell me if you have any problem.

**Comment by kasperaamodt** [comment]
Thank you so much.

**Comment by louisabraham** [comment]
@kasperaamodt so, did it work?

**Comment by kasperaamodt** [comment]
Yes!

**Comment by louisabraham** [comment]
Awesome!

**Comment by kasperaamodt** [comment]
ffpass import: error: the following arguments are required: -d/--directory/--dir 

how do I solve this?

**Comment by kasperaamodt** [comment]
Never mind, I added --dir + Firefox profile from finder to the end of the command line and it worked.

**Comment by ymatuhin** [comment]
>     3\. ffpass import -f

Hey, sorry for bothering. I've installed the lib but now I'm getting the error `zsh: command not found: ffpass`. Any ideas?

**Comment by 93493** [comment]
Hello, i also dont know how it works. I start Python type in pip install ffpass and get the message 
File "stdin", line 1
pip install ffpass
^
Syntax Error: invalid syntax

What i can do?

**Comment by louisabraham** [comment]
You should launch that command in a terminal, not in Python.

**Comment by 93493** [comment]
Terminal? CMD? I tried. I gave python in and this comes 

C:\Users\01>python

C:\Users\01>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install ffpass
  File "<stdin>", line 1
    pip install ffpass
              ^

**Comment by louisabraham** [comment]
Just type "pip install ffpass" in the terminal.

**Comment by 93493** [comment]
"ffpass -d C:\Users\MYPC\AppData\Roaming\Mozilla\Firefox\Profiles\korwo2.default export > passwords.csv" 

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 12-13: truncated \UXXXXXXXX escape

**Comment by louisabraham** [comment]
That's a classical error: https://stackoverflow.com/a/1347854/5133167

**Comment by 93493** [comment]
No more Errors yet but i cant find the file passwords.csv

**Comment by louisabraham** [comment]
It should be in the current directory (probably `C:\Users\01`)

**Comment by 93493** [comment]
Not there. I'm using the search tool Everything if you know it. Nowhere is a file with the name password.csv. What i'm doing wrong?

**Comment by louisabraham** [comment]
Just replace `> password.csv` with the full path of the target file. I cannot help you much more, your issue is not related to ffpass.

**Comment by 93493** [comment]
This is the full string now 

"ffpass -d C:\\Users\\01\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\vzcnbzh2.default export > passwords.csv"

I copied the folder to C:\

"ffpass -d C:\\vzcnbzh2.default export > passwords.csv"

But the same. No csv file

Because i'm doing this all is i wanted to update Firefox from 72 to 73 but i can't. After i installed Firefox 73, all my Passes are gone. So i wanted to export my passes out of 72 and re-import it to 73. Copy key4.db and logins.json from 72 to 73 not working as well. My passwords have a Master Password. I can't change it. I couldnt find any tool that can import, only export.

**Comment by louisabraham** [comment]
note: you can put code into backticks "`"

What about `ffpass -d C:\\Users\\01\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\vzcnbzh2.default export > C:\\Users\\01\\passwords.csv` ?

**Comment by 93493** [comment]
Nothing. I give up...

**Comment by 93493** [comment]
I tried it with Firefox Portable 

"pip install ffpass"
"ffpass -d C:\FirefoxPortable\Data\profile export > passwords.csv"

The same. I have the feeling something is wrong with Python?!

**Comment by 93493** [comment]
Im coming closer. I typed the whole time python in CMD. Now i typed just 

ffpass -d C:\Users\01\AppData\Roaming\Mozilla\Firefox\Profiles\vzcnbzh2.default export > passwords.csv

and ive got a passwords file but its empty and error message in cmd is

C:\Users\01>ffpass -d C:\Users\01\AppData\Roaming\Mozilla\Firefox\Profiles\vzcnbzh2.default export > passwords.csv
usage: ffpass [-h] {export,import} ...
ffpass: error: argument mode: invalid choice: 'C:\\Users\\01\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\vzcnbzh2.default' (choose from 'export', 'import')

**Comment by 93493** [comment]
Okay next problem lol. Import not working

C:\Users\01>ffpass import --from passwords.csv -d "C:\Users\01\AppData\Roaming\Mozilla\Firefox\Profiles\vzcnbzh2.default"
Firefox password database is empty. Please create it from Firefox.

**Comment by 93493** [comment]
So. I installed new Firefox 73 and deleted all old Profile Folders. 

Now this

C:\Users\01>ffpass import < passwords.csv -d "C:\Users\01\AppData\Roaming\Mozilla\Firefox\Profiles\iaz2r3kb.default-release"
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\ffpass.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\ffpass\__init__.py", line 354, in main
    args.func(args)
  File "c:\python38\lib\site-packages\ffpass\__init__.py", line 278, in main_import
    key = getKey(args.directory)
  File "c:\python38\lib\site-packages\ffpass\__init__.py", line 74, in getKey
    entrySalt = decodedItem2[0][1][0].asOctets()
AttributeError: 'Sequence' object has no attribute 'asOctets'

???

**Comment by louisabraham** [comment]
Glad it worked!

This is a known bug https://github.com/louisabraham/ffpass/issues/49 that might or not be fixed in the future. The cause is that FF changed the way they store passwords.

**Comment by 93493** [comment]
I went back to 72, imported the Passwords, updated to 73 and now i have finally the Passwords there.

**Comment by nrvnzsmbruch** [comment]
Hey, my problem is i have never used python before. I managed to 

`pip install ffpass`

but then when i try using `ffpass import < export.csv`

it just says that it can't find it or that it's misspelled.
