### ISSUE TITLE
Does not work when used inside firejail

### ISSUE THREAD

**Issue by BenWibking** [louisabraham/ffpass#22]
For security reasons, many users would want to use this within a sandbox environment, such as firejail. However, I can't get it to work, even after whitelisting my Firefox profile directory:

```
firejail $HOME/.local/bin/ffpass import --from chrome-passwords.csv --directory .mozilla/firefox/6yc899yq.default
```

where my Firejail profile for ffpass includes:

```
whitelist ${HOME}/.local/lib/python3.7/site-packages/ffpass
whitelist ${HOME}/.local/lib/python3.7/site-packages/pyasn1
whitelist ${HOME}/.local/bin/ffpass
whitelist ${HOME} .mozilla/firefox/6yc899yq.default/key4.db
whitelist ${HOME} .mozilla/firefox/6yc899yq.default/logins.json
whitelist ${HOME}/chrome-passwords.csv
```

**Comment by louisabraham** [comment]
Hi, I don't know anything about firejail.
You should probably whitelist the whole python3.7 directory, or at least the pycryptodome folder.

Do you have any error message?

**Comment by louisabraham** [comment]
Also, I don't see why anyone would be concerned by security, the code is open source and has less than 300 SLOC.

**Comment by BenWibking** [comment]
I've read the code in this repo, but I haven't read the code for all of the dependencies, the python interpreter, all of its dependencies... we'll just have to agree to disagree about our philosophy of security I guess.

It says:
```
Firefox password database is empty. Please create it from Firefox.
```

When I re-try with a dummy password file without using Firejail, it works.

**Comment by louisabraham** [comment]
This is error is triggered by the following code:

```
from pathlib import Path

dbfile = Path(".mozilla/firefox/6yc899yq.default/key4.db")
assert dbfile.exists()
```

**Comment by louisabraham** [comment]
I don't understand where your .mozilla folder is.  is in your home, didn't you forget a slash in your whitelist?

**Comment by BenWibking** [comment]
Hmm, that was a typo, yes. I've fixed it, but the code snippet still gives me an error:

```
Traceback (most recent call last):
  File "/home/ben/.local/bin/sandbox_test", line 5, in <module>
    assert dbfile.exists()
  File "/usr/lib/python3.7/pathlib.py", line 1339, in exists
    self.stat()
  File "/usr/lib/python3.7/pathlib.py", line 1161, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '.mozilla/firefox/6yc899yq.default/key4.db'
```

**Comment by louisabraham** [comment]
Path uses os.stat so the following code has to work as well:

```python
import os

os.stat(".mozilla/firefox/6yc899yq.default/key4.db")
```

Maybe it will work if you provide the fullpath instead of the relative one?

**Comment by BenWibking** [comment]
Ok, so the whole directory tree inside .mozilla needs to be both noblacklisted and whitelisted. For future reference, putting the following at the top of the Firejail profile works:

```noblacklist ${HOME}/.mozilla
noblacklist ${HOME}/.mozilla/firefox
noblacklist ${HOME}/.mozilla/firefox/6yc899yq.default
noblacklist ${HOME}/.mozilla/firefox/6yc899yq.default/key4.db
noblacklist ${HOME}/.mozilla/firefox/6yc899yq.default/logins.json
whitelist ${HOME}/.mozilla/firefox/6yc899yq.default/key4.db
whitelist ${HOME}/.mozilla/firefox/6yc899yq.default/logins.json
```

**Comment by louisabraham** [comment]
Great!
