### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by robahearts** [louisabraham/ffpass#23]
I keep getting this message

> ERROR: Could not find a version that satisfies the requirement ffpass (from versions: none)
> ERROR: No matching distribution found for ffpass

My system info: 
Firefox 67.0.4
MacOS Mojave

**Comment by louisabraham** [comment]
I think you don't have a compatible version of Python.

Install Python 3 from https://www.python.org/

**Comment by ositanachi** [comment]
Download the latest version of Python and use "pip3" instead of "pip".

**Comment by Bacham** [comment]
I keep getting this message

> sudo pip3 install ffpass
> Collecting ffpass
  Could not find a version that satisfies the requirement ffpass (from versions: )
No matching distribution found for ffpass

My system info:
ubuntu 17.04
python 3.6
firefox 68

**Comment by louisabraham** [comment]
Hi, this is strange. Can you try with

    python3 -m pip install --user ffpass

**Comment by Bacham** [comment]
I tryed it and get exactly the same error.
Thanks for your help

**Comment by robahearts** [comment]
> Hi, this is strange. Can you try with
> 
> ```
> python3 -m pip install --user ffpass
> ```

This worked for me.

Thanks.

**Comment by louisabraham** [comment]
It probably means that `pip3` is not associated with the right python version (you might have several python 3 installations).  You can use `which` and `readlink` to understand the problem.

@robahearts I'm closing this issue but don't hesitate if you still have problems.

**Comment by Bacham** [comment]
Yes I've python 3.5 installed which is the default python version on ubuntu 17.04, the solution is:
`python3.6 /usr/bin/pip install ffpass` 

then to run ffpass:
`python3.6 ~/.local/bin/ffpass`

Please add this to readme.md
