### ISSUE TITLE
Doesn't work with Firefox Lockwise (password syncing)

### ISSUE THREAD

**Issue by zog2** [louisabraham/ffpass#25]
Hello, thanks for this useful tool. 

I've noticed that the passwords that I've imported from Chrome into Firefox will not sync over when using Firefox's password syncing tool, Firefox Lockwise (https://lockwise.firefox.com/). All the other passwords I had from before using ffpass sync'ed over, but none of the passwords that came from the import sync'ed.

Maybe there is some flag Firefox has attached to Firefox-created passwords that ffpass cannot handle? Any suggestions on a fix/workaround are appreciated, thanks.

**Comment by louisabraham** [comment]
Hi, how much time did you wait?

**Comment by zog2** [comment]
It's been 2 weeks since I set it up. I've tried all the Firefox Lockwise troubleshooting, but nothing fixes it. Do you use Lockwise and have it working?

**Comment by louisabraham** [comment]
No, I have never used Lockwise.

**Comment by louisabraham** [comment]
What if you try uninstalling and reinstalling Lockwise in the browser?

**Comment by zog2** [comment]
Yes, still did not work with un/reinstall

**Comment by ositanachi** [comment]
Albeit a slightly different issue, I am curious about this since it does not seem the passwords I imported from Chrome sync to other devices.

I’ll try to do some digging.

Curious, does your imported passwords appear on other devices? @zog2

**Comment by louisabraham** [comment]
Closing this since #28 is solved.
