### ISSUE TITLE
Imported passwords does not sync with other devices

### ISSUE THREAD

**Issue by ositanachi** [louisabraham/ffpass#28]
Feel free to merge with issue #11. 

I successfully imported passwords from a csv I exported from Chrome into Firefox on my MacOS device. Unfortunately the logins does not sync with my iPhone. The only login credentials that I have access to via sync are those saved using Firefox.

Reconnecting my Firefox account on my iPhone does not help. This issue seems to be affecting lockwise as well as noted in #25.

**Comment by WesleyBatista** [comment]
I managed to get the passwords in sync.

what I did:
- reinstall firefox (without setting up the firefox sync)
- find out where my firefox profile directory is located
- run:
  ```ffpass import --from 'Chrome Passwords.csv' -d /home/wesley/.mozilla/firefox/pth337gw.default-release```
- sign in with my firefox sync account

Then everything started to appear on Lockwise as well. 

good luck buddies! :pray:

**Comment by ositanachi** [comment]
Huzzah! That did the trick, thank you.

**Comment by Lanchon** [comment]
## no need to reinstall or clear your profile or set up a new profile

- i simply disconnected SYNC from firefox sync options,
- imported the passwords,
- changed one imported password (i don't know if this is needed)
- reconnected SYNC
- forced a "sync now"

and all imported passwords synced to other devices.

remember to force "sync now" on other devices to see them ASAP.

**Comment by fregante** [comment]
Even fewer steps. You just need to disconnect and reconnect the account, basically. Here's what I did

1. Import passwords
2. Disconnect sync account (`about:preferences#sync`)
3. Restart browser (maybe not needed)
4. Connect sync account
