### ISSUE TITLE
Key Error 'url'

### ISSUE THREAD

**Issue by Maartz** [louisabraham/ffpass#31]
Hey, 

I've encountered an error during the import of a CSV file.

That's the output of my command : `ffpass import --from example.csv --verbose`

```
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 346, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 289, in main_import
    logins = readCSV(args.from_file)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 188, in readCSV
    logins.append((rawURL(row["url"]), row["username"], row["password"]))
KeyError: 'url'
```

Even though I've the latest Python version and solved the trouble I've had with the Firefox profiles. Do you have any idea ?

Thanks !

**Comment by louisabraham** [comment]
Hi, can you paste the first line of `example.csv`?

**Comment by 0xphk** [comment]
For me the first line starts with 'hostname' instead of 'url' so changing this fixed the error. 
But no passwords were imported in my case, I'm guessing the ff password exporter from which I created my backup isn't compatible with your importer. Can give more information on monday

**Comment by louisabraham** [comment]
There shouldn't be any compatibility problem. My importer handles any CSV file.

**Comment by 0xphk** [comment]
Maybe it has something to do with master password encrypted passwords. Copying the whole Firefox profile to a new machine for testing showed that passwords did not show up in Firefox, though the corresponding files (key4.db/logins.json) were still there. Bookmarks and settings instead are all in place as expected. Did things change in Firefox 69?

Export worked with kspearrin's ff-password-exporter as we had no python available on this windows box. After fixing the csv fieldname from 'hostname' to 'url' the import seemed like working, no error message at all but same as importing the whole profile > no passwords visible in firefox at all.

Any hint how to debug this issue further? If additional info is needed, I would be happy to help.

**Comment by louisabraham** [comment]
I don't know about copying the whole profile. 

You can try the steps described there: https://github.com/louisabraham/ffpass/issues/28#issuecomment-512769781

**Comment by louisabraham** [comment]
Closing this for now, don't hesitate to reopen if you still have problems @0xphk
