### ISSUE TITLE
'There is more than one profile' while tring to export

### ISSUE THREAD

**Issue by MaximeL** [louisabraham/ffpass#33]
Hello,

I tried to export doing this command :  
`ffpass export -t passwords.csv -d . -v`  

The output was :  
`There is more than one profile`  

I run Python 3.7.4 on windows 10 and firefox 69.0.1 (64-bit)

**Comment by louisabraham** [comment]
I think `-d .` is incorrect. What happens without this option?

**Comment by MaximeL** [comment]
`ffpass export -t passwords.csv -v`  
result :  
```
There is more than one profile
usage: ffpass export [-h] [-t TO_FILE] -d DIRECTORY [-v]
ffpass export: error: the following arguments are required: -d/--directory/--dir
```

`-d/--directory/--dir ` seems mandatory

**Comment by louisabraham** [comment]
Then you need to locate your profile directory: https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data

**Comment by MaximeL** [comment]
I did
`ffpass export -t passwords.csv -v -d <profile_dir_path>`

it worked, thanks.
