### ISSUE TITLE
ffpass on Windows

### ISSUE THREAD

**Issue by scofield8610** [louisabraham/ffpass#38]
Hi,
i tried to import an csv-file with passwords to Firefox.

So I installed on my windows-system Python 3.8 and downloaded ffpass.

But now i really don´t know what I have to do with the .py-file.

I hope somene can help me by this way?

Best regards
Scofield

**Comment by louisabraham** [comment]
Hi, you just have to use the command line (https://www.lifewire.com/command-prompt-2625840) and launch ffpass from it!

**Comment by scofield8610** [comment]
Hi louisabraham,
thanks for your respond.
So I drag´n drop the file __init__.py into command prompt.

There I get the message 

`Traceback (most recent call last):
  File "C:\Users\User\Desktop\ffpass-master\ffpass-master\ffpass\__init__.py", line 43, in <module>
    from pyasn1.codec.der.decoder import decode as der_decode
ModuleNotFoundError: No module named 'pyasn1'`

I think that at first i have to configure the file __init__.py by opening via "Edit with IDLE".
But iI don´t know what for parameters are the right one for the import to FF.

**Comment by louisabraham** [comment]
Hi Scofield,

You should first install it with `pip3 install ffpass`, then you can use the command ffpass as described in the front page.

If you need further help, I suggest you to ask the friendly people of https://pythondiscord.com/. They are awesome and will chat with you until you resolve your issue!

But you can always ask questions here if you need or prefer.

**Comment by louisabraham** [comment]
Closing this inactive thread.
