### ISSUE TITLE
CSV format compatibility problem

### ISSUE THREAD

**Issue by wayou** [louisabraham/ffpass#4]
Not working with the chrome exported csv which with the following foramt:

```
name,url,username,password
```

the import action prints fails with message below:

```bash
$ ffpass import --from my_chrome_pswds.csv
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 292, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 251, in main_import
    logins = readCSV(args.from_file)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 161, in readCSV
    logins.append((rawURL(row['url']),
KeyError: 'url'
```

However, I managed to import by modifying the format:
- remove the header line
- remove the name column for each entry

**Comment by louisabraham** [comment]
How did you export the passwords from Google Chrome ?

As specified in the usage:

    imports a CSV with columns `url,username,password` (order insensitive)

I thought Chrome exports without name. Are you sure it works when removing the header line?

**Comment by wayou** [comment]
you can export chrome passwords from the dropdown menu in the setting page chrome://settings/passwords

**Comment by louisabraham** [comment]
Yes, normally it works with the data exported from chrome. Even if you add columns.

It worked with the file I exported from Chrome.

Could you produce a minimal example?

Something like

    name,url,username,password
    fake,fake,fake,fake

**Comment by wayou** [comment]
My bad. Cannot reproduce now. Only if I remove the header line the error coccus.
I  though it might be that I removed the header from the exported data before. 😅 

Thanks for the great tool.

**Comment by louisabraham** [comment]
Yes, it needs the headers.
On the other hand, even if you permute or add columns it still works.

Glad it helped you!
