### ISSUE TITLE
Can't import passwords from Chromium

### ISSUE THREAD

**Issue by bartlebi** [louisabraham/ffpass#53]
When i trying to import passwords with that command
`~/.local/bin/ffpass import --from passes.csv `
it says 
```
usage: ffpass import [-h] [-f FROM_FILE] -d DIRECTORY [-v]
ffpass import: error: the following arguments are required: -d/--directory/--dir
```
I tried to start it with -d argument, but see next error:
~/.local/bin/ffpass import --from passes.csv -d ~/.mozilla/firefox/81dhfo76.default-release/
```
Traceback (most recent call last):
  File "/home/bartlebi/.local/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/home/bartlebi/.local/lib/python3.8/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/home/bartlebi/.local/lib/python3.8/site-packages/ffpass/__init__.py", line 287, in main_import
    key = askpass(args.directory)
  File "/home/bartlebi/.local/lib/python3.8/site-packages/ffpass/__init__.py", line 254, in askpass
    key = getKey(directory, password)
  File "/home/bartlebi/.local/lib/python3.8/site-packages/ffpass/__init__.py", line 93, in getKey
    entrySalt = decodedA11[0][1][0].asOctets()
AttributeError: 'Sequence' object has no attribute 'asOctets'
```
Whats wrong?
I tried to use antoher one likely profile directory in this locations
`~/.local/bin/ffpass import --from passes.csv -d ~/.mozilla/firefox/718lhm58.default/`
but ffpass says

`Firefox password database is empty. Please create it from Firefox.`

**Comment by JPUnD** [comment]
Having exactly the same issue, trying to create a random password on the password manager doesn't solve it.

System:
- Distro: Manjaro 
- WM: i3
- Firefox: 79.0
- Kernel: 5.4.57
- x86_64

**Comment by bartlebi** [comment]
> Having exactly the same issue, trying to create a random password on the password manager doesn't solve it.
> 
> System:
> 
> * Distro: Manjaro
> * WM: i3
> * Firefox: 79.0
> * Kernel: 5.4.57
> * x86_64

The solution is to install the newest beta version of firefox with import and export added.
As I understood the problem is in the changed encryption method in firefox.
