### ISSUE TITLE
ffpass command not found

### ISSUE THREAD

**Issue by jcpirate76** [louisabraham/ffpass#69]
What am I doing wrong here? PS be gentle, I'm a total noob at linux script

WARNING: The script ffpass is installed in '/home/crutchlowje/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed ffpass-0.5.0 pyasn1-0.4.8 pycryptodome-3.17
crutchlowje@penguin:~$ ffpass import --file passwords.csv
-bash: ffpass: command not found
crutchlowje@penguin:~$ export PATH=/home/crutchlowje/local.bin:$PATH
crutchlowje@penguin:~$ ffpass import --file passwords.csv
-bash: ffpass: command not found

**Comment by louisabraham** [comment]
The first step is to read the warning. You just have to add `/home/crutchlowje/.local/bin` to PATH. Here is a useful tutorial: https://www.baeldung.com/linux/path-variable

Good luck learning Linux!

**Comment by louisabraham** [comment]
Btw, your prompt indicates that you are using Bash.
