### ISSUE TITLE
can't import CSV from Chrome to Firefox

### ISSUE THREAD

**Issue by Prutheus** [louisabraham/ffpass#8]
Python 3.7, Firefox 58:

`ffpass import --from "Chrome Passwords.csv"`

ERROR:

```
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 335, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 276, in main_import
    key = askpass(args.directory)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 243, in askpass
    key = getKey(directory, password)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 85, in getKey
    row = next(c)
StopIteration
```

**Comment by louisabraham** [comment]
Hi, I think it is the same issue as in #6 

Adding a new password into Firefox will create the database and it will solve the issue.

However this error should show a more explicit error. What are your OS and the version of ffpass?

**Comment by drws** [comment]
I'm confirming this as a separate issue with Python 3.7.1, Firefox 64.0 and ffpass 0.4.2. I already have a few passwords stored in Firefox and I wanted to add more. The error is the same as in the orignal post. The ffpass' error that the pasword DB is empty is not printed. 

OS shouldn't matter but I can add that it is an updated Arch Linux (rolling release, no versions).

**Comment by louisabraham** [comment]
Maybe #10 solves that. I just deployed it in version 0.4.3, can you test?

**Comment by drws** [comment]
Well, for me it definitely does solve it :) I only updated ffpass to 0.4.3 through pip (sudo pip install --upgrade ffpass) and the import worked right away. I also tested export which works as it should. Thank you for a quick response and the great work on this tool!

**Comment by louisabraham** [comment]
Glad it worked for you @drws.
We should thank @prekageo who diagnosed and fixed this!
I'm closing this issue for the moment, but @Prutheus feel free to reopen it.
