### ISSUE TITLE
safari to firefox on macOS

### ISSUE THREAD

**Issue by pabclsn** [louisabraham/ffpass#9]
hey,

I'm getting a csv from this tool https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

with url; username;password

and I'm getting this error.

Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 335, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 278, in main_import
    logins = readCSV(args.from_file)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 178, in readCSV
    logins.append((rawURL(row["url"]), row["username"], row["password"]))
KeyError: 'url'

;)

**Comment by louisabraham** [comment]
Hi, according to the documentation, your CSV must have column names

    url,username,password

and the separator must be comas, not semicolons.

If your passwords do not contain any semicolons, I think you can just replace all semicolons by comas in your text file. Else, you can convert it by hand with python (if you know it) or use any spreadsheet software that supports csv format.

**Comment by pabclsn** [comment]
ok I'll try thanks ;)

**Comment by pabclsn** [comment]
no error during execution, but the url (www or without) are not loaded in db ... do I need http:// ?
![capture d ecran 2018-12-10 a 21 42 27](https://user-images.githubusercontent.com/25625769/49760376-9fd31300-fcc4-11e8-953b-6625f1d2ee50.png)

**Comment by louisabraham** [comment]
Can I see the first 5 lines (with different usernames / passwords) of your CSV file?

**Comment by pabclsn** [comment]
yes :)

`url,username,password
secure.galerieslafayette.com,colson.pablo@icloud.com,xxxxxxxxxxxxxxxx 
gitlab.epsi-nantes.fr,pablo.colson,xxxxxxxxxxxxxxxx
ecampusnantes.epsi.fr,pablo.colson,xxxxxxxxxxxxxxxx
n39.network-auth.com,pablo.colson,xxxxxxxxxxxxxxxx
e5.onthehub.com,pablo.colson,xxxxxxxxxxxxxxxx`

**Comment by louisabraham** [comment]
Oh, yes, you need `http://`. I'll add it to the doc!

**Comment by pabclsn** [comment]
ok ;)
 thanks :)

**Comment by louisabraham** [comment]
It's not even a bug but a feature: some websites support multiple schemes (for example ftp and https). For example, internet boxes have both a https (or http) admin interface, and a ftp multimedia server, and both can have different passwords.

**Comment by louisabraham** [comment]
Did it work?

**Comment by pabclsn** [comment]
100% thanks a lot ;)
